#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

git ls-files --others --error-unmatch docs >/dev/null 2>&1; ec=$?
if test "$ec" = 0; then
    git commit -am 'auto build'
elif test "$ec" = 1; then
    echo no untracked files
else
    echo error from ls-files
fi
